//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace MAS {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("Ds_Residence_Account_Print")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class Ds_Residence_Account_Print : global::System.Data.DataSet {
        
        private DS_RESIDENCE_ACCOUNT_PRINTDataTable tableDS_RESIDENCE_ACCOUNT_PRINT;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public Ds_Residence_Account_Print() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected Ds_Residence_Account_Print(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["DS_RESIDENCE_ACCOUNT_PRINT"] != null)) {
                    base.Tables.Add(new DS_RESIDENCE_ACCOUNT_PRINTDataTable(ds.Tables["DS_RESIDENCE_ACCOUNT_PRINT"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public DS_RESIDENCE_ACCOUNT_PRINTDataTable DS_RESIDENCE_ACCOUNT_PRINT {
            get {
                return this.tableDS_RESIDENCE_ACCOUNT_PRINT;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            Ds_Residence_Account_Print cln = ((Ds_Residence_Account_Print)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["DS_RESIDENCE_ACCOUNT_PRINT"] != null)) {
                    base.Tables.Add(new DS_RESIDENCE_ACCOUNT_PRINTDataTable(ds.Tables["DS_RESIDENCE_ACCOUNT_PRINT"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableDS_RESIDENCE_ACCOUNT_PRINT = ((DS_RESIDENCE_ACCOUNT_PRINTDataTable)(base.Tables["DS_RESIDENCE_ACCOUNT_PRINT"]));
            if ((initTable == true)) {
                if ((this.tableDS_RESIDENCE_ACCOUNT_PRINT != null)) {
                    this.tableDS_RESIDENCE_ACCOUNT_PRINT.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void InitClass() {
            this.DataSetName = "Ds_Residence_Account_Print";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/Ds_Residence_Account_Print.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableDS_RESIDENCE_ACCOUNT_PRINT = new DS_RESIDENCE_ACCOUNT_PRINTDataTable();
            base.Tables.Add(this.tableDS_RESIDENCE_ACCOUNT_PRINT);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private bool ShouldSerializeDS_RESIDENCE_ACCOUNT_PRINT() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            Ds_Residence_Account_Print ds = new Ds_Residence_Account_Print();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public delegate void DS_RESIDENCE_ACCOUNT_PRINTRowChangeEventHandler(object sender, DS_RESIDENCE_ACCOUNT_PRINTRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class DS_RESIDENCE_ACCOUNT_PRINTDataTable : global::System.Data.TypedTableBase<DS_RESIDENCE_ACCOUNT_PRINTRow> {
            
            private global::System.Data.DataColumn columnRECEIPTNO;
            
            private global::System.Data.DataColumn columnRECEIPTDATE;
            
            private global::System.Data.DataColumn columnRECEIPTREFNO;
            
            private global::System.Data.DataColumn columnRECEIPTRID;
            
            private global::System.Data.DataColumn columnFINYEAR;
            
            private global::System.Data.DataColumn columnRECEIPTYEAR;
            
            private global::System.Data.DataColumn columnRECEIPTMONTH;
            
            private global::System.Data.DataColumn columnFORTHEYEAR;
            
            private global::System.Data.DataColumn columnSUBSCRIPTION;
            
            private global::System.Data.DataColumn columnSALARY;
            
            private global::System.Data.DataColumn columnFOODEXPENSE;
            
            private global::System.Data.DataColumn columnCONTRIBUTION;
            
            private global::System.Data.DataColumn columnEIDALFITR;
            
            private global::System.Data.DataColumn columnEIDALADHA;
            
            private global::System.Data.DataColumn columnCOCUNUT;
            
            private global::System.Data.DataColumn columnOTHER;
            
            private global::System.Data.DataColumn columnTOTALAMOUNT;
            
            private global::System.Data.DataColumn columnRECEIPTTYPE;
            
            private global::System.Data.DataColumn columnRECEIPTDETAILS;
            
            private global::System.Data.DataColumn columnREMARKS;
            
            private global::System.Data.DataColumn columnPRINTED;
            
            private global::System.Data.DataColumn columnSTATUS;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public DS_RESIDENCE_ACCOUNT_PRINTDataTable() {
                this.TableName = "DS_RESIDENCE_ACCOUNT_PRINT";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal DS_RESIDENCE_ACCOUNT_PRINTDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected DS_RESIDENCE_ACCOUNT_PRINTDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn RECEIPTNOColumn {
                get {
                    return this.columnRECEIPTNO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn RECEIPTDATEColumn {
                get {
                    return this.columnRECEIPTDATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn RECEIPTREFNOColumn {
                get {
                    return this.columnRECEIPTREFNO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn RECEIPTRIDColumn {
                get {
                    return this.columnRECEIPTRID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn FINYEARColumn {
                get {
                    return this.columnFINYEAR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn RECEIPTYEARColumn {
                get {
                    return this.columnRECEIPTYEAR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn RECEIPTMONTHColumn {
                get {
                    return this.columnRECEIPTMONTH;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn FORTHEYEARColumn {
                get {
                    return this.columnFORTHEYEAR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn SUBSCRIPTIONColumn {
                get {
                    return this.columnSUBSCRIPTION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn SALARYColumn {
                get {
                    return this.columnSALARY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn FOODEXPENSEColumn {
                get {
                    return this.columnFOODEXPENSE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn CONTRIBUTIONColumn {
                get {
                    return this.columnCONTRIBUTION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn EIDALFITRColumn {
                get {
                    return this.columnEIDALFITR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn EIDALADHAColumn {
                get {
                    return this.columnEIDALADHA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn COCUNUTColumn {
                get {
                    return this.columnCOCUNUT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn OTHERColumn {
                get {
                    return this.columnOTHER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn TOTALAMOUNTColumn {
                get {
                    return this.columnTOTALAMOUNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn RECEIPTTYPEColumn {
                get {
                    return this.columnRECEIPTTYPE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn RECEIPTDETAILSColumn {
                get {
                    return this.columnRECEIPTDETAILS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn REMARKSColumn {
                get {
                    return this.columnREMARKS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn PRINTEDColumn {
                get {
                    return this.columnPRINTED;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn STATUSColumn {
                get {
                    return this.columnSTATUS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public DS_RESIDENCE_ACCOUNT_PRINTRow this[int index] {
                get {
                    return ((DS_RESIDENCE_ACCOUNT_PRINTRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event DS_RESIDENCE_ACCOUNT_PRINTRowChangeEventHandler DS_RESIDENCE_ACCOUNT_PRINTRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event DS_RESIDENCE_ACCOUNT_PRINTRowChangeEventHandler DS_RESIDENCE_ACCOUNT_PRINTRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event DS_RESIDENCE_ACCOUNT_PRINTRowChangeEventHandler DS_RESIDENCE_ACCOUNT_PRINTRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event DS_RESIDENCE_ACCOUNT_PRINTRowChangeEventHandler DS_RESIDENCE_ACCOUNT_PRINTRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void AddDS_RESIDENCE_ACCOUNT_PRINTRow(DS_RESIDENCE_ACCOUNT_PRINTRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public DS_RESIDENCE_ACCOUNT_PRINTRow AddDS_RESIDENCE_ACCOUNT_PRINTRow(
                        string RECEIPTNO, 
                        string RECEIPTDATE, 
                        string RECEIPTREFNO, 
                        string RECEIPTRID, 
                        string FINYEAR, 
                        string RECEIPTYEAR, 
                        string RECEIPTMONTH, 
                        string FORTHEYEAR, 
                        string SUBSCRIPTION, 
                        string SALARY, 
                        string FOODEXPENSE, 
                        string CONTRIBUTION, 
                        string EIDALFITR, 
                        string EIDALADHA, 
                        string COCUNUT, 
                        string OTHER, 
                        string TOTALAMOUNT, 
                        string RECEIPTTYPE, 
                        string RECEIPTDETAILS, 
                        string REMARKS, 
                        string PRINTED, 
                        string STATUS) {
                DS_RESIDENCE_ACCOUNT_PRINTRow rowDS_RESIDENCE_ACCOUNT_PRINTRow = ((DS_RESIDENCE_ACCOUNT_PRINTRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        RECEIPTNO,
                        RECEIPTDATE,
                        RECEIPTREFNO,
                        RECEIPTRID,
                        FINYEAR,
                        RECEIPTYEAR,
                        RECEIPTMONTH,
                        FORTHEYEAR,
                        SUBSCRIPTION,
                        SALARY,
                        FOODEXPENSE,
                        CONTRIBUTION,
                        EIDALFITR,
                        EIDALADHA,
                        COCUNUT,
                        OTHER,
                        TOTALAMOUNT,
                        RECEIPTTYPE,
                        RECEIPTDETAILS,
                        REMARKS,
                        PRINTED,
                        STATUS};
                rowDS_RESIDENCE_ACCOUNT_PRINTRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowDS_RESIDENCE_ACCOUNT_PRINTRow);
                return rowDS_RESIDENCE_ACCOUNT_PRINTRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                DS_RESIDENCE_ACCOUNT_PRINTDataTable cln = ((DS_RESIDENCE_ACCOUNT_PRINTDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new DS_RESIDENCE_ACCOUNT_PRINTDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal void InitVars() {
                this.columnRECEIPTNO = base.Columns["RECEIPTNO"];
                this.columnRECEIPTDATE = base.Columns["RECEIPTDATE"];
                this.columnRECEIPTREFNO = base.Columns["RECEIPTREFNO"];
                this.columnRECEIPTRID = base.Columns["RECEIPTRID"];
                this.columnFINYEAR = base.Columns["FINYEAR"];
                this.columnRECEIPTYEAR = base.Columns["RECEIPTYEAR"];
                this.columnRECEIPTMONTH = base.Columns["RECEIPTMONTH"];
                this.columnFORTHEYEAR = base.Columns["FORTHEYEAR"];
                this.columnSUBSCRIPTION = base.Columns["SUBSCRIPTION"];
                this.columnSALARY = base.Columns["SALARY"];
                this.columnFOODEXPENSE = base.Columns["FOODEXPENSE"];
                this.columnCONTRIBUTION = base.Columns["CONTRIBUTION"];
                this.columnEIDALFITR = base.Columns["EIDALFITR"];
                this.columnEIDALADHA = base.Columns["EIDALADHA"];
                this.columnCOCUNUT = base.Columns["COCUNUT"];
                this.columnOTHER = base.Columns["OTHER"];
                this.columnTOTALAMOUNT = base.Columns["TOTALAMOUNT"];
                this.columnRECEIPTTYPE = base.Columns["RECEIPTTYPE"];
                this.columnRECEIPTDETAILS = base.Columns["RECEIPTDETAILS"];
                this.columnREMARKS = base.Columns["REMARKS"];
                this.columnPRINTED = base.Columns["PRINTED"];
                this.columnSTATUS = base.Columns["STATUS"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            private void InitClass() {
                this.columnRECEIPTNO = new global::System.Data.DataColumn("RECEIPTNO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRECEIPTNO);
                this.columnRECEIPTDATE = new global::System.Data.DataColumn("RECEIPTDATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRECEIPTDATE);
                this.columnRECEIPTREFNO = new global::System.Data.DataColumn("RECEIPTREFNO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRECEIPTREFNO);
                this.columnRECEIPTRID = new global::System.Data.DataColumn("RECEIPTRID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRECEIPTRID);
                this.columnFINYEAR = new global::System.Data.DataColumn("FINYEAR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFINYEAR);
                this.columnRECEIPTYEAR = new global::System.Data.DataColumn("RECEIPTYEAR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRECEIPTYEAR);
                this.columnRECEIPTMONTH = new global::System.Data.DataColumn("RECEIPTMONTH", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRECEIPTMONTH);
                this.columnFORTHEYEAR = new global::System.Data.DataColumn("FORTHEYEAR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFORTHEYEAR);
                this.columnSUBSCRIPTION = new global::System.Data.DataColumn("SUBSCRIPTION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSUBSCRIPTION);
                this.columnSALARY = new global::System.Data.DataColumn("SALARY", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSALARY);
                this.columnFOODEXPENSE = new global::System.Data.DataColumn("FOODEXPENSE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFOODEXPENSE);
                this.columnCONTRIBUTION = new global::System.Data.DataColumn("CONTRIBUTION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCONTRIBUTION);
                this.columnEIDALFITR = new global::System.Data.DataColumn("EIDALFITR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEIDALFITR);
                this.columnEIDALADHA = new global::System.Data.DataColumn("EIDALADHA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEIDALADHA);
                this.columnCOCUNUT = new global::System.Data.DataColumn("COCUNUT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOCUNUT);
                this.columnOTHER = new global::System.Data.DataColumn("OTHER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOTHER);
                this.columnTOTALAMOUNT = new global::System.Data.DataColumn("TOTALAMOUNT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTOTALAMOUNT);
                this.columnRECEIPTTYPE = new global::System.Data.DataColumn("RECEIPTTYPE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRECEIPTTYPE);
                this.columnRECEIPTDETAILS = new global::System.Data.DataColumn("RECEIPTDETAILS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRECEIPTDETAILS);
                this.columnREMARKS = new global::System.Data.DataColumn("REMARKS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREMARKS);
                this.columnPRINTED = new global::System.Data.DataColumn("PRINTED", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPRINTED);
                this.columnSTATUS = new global::System.Data.DataColumn("STATUS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTATUS);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public DS_RESIDENCE_ACCOUNT_PRINTRow NewDS_RESIDENCE_ACCOUNT_PRINTRow() {
                return ((DS_RESIDENCE_ACCOUNT_PRINTRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new DS_RESIDENCE_ACCOUNT_PRINTRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(DS_RESIDENCE_ACCOUNT_PRINTRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.DS_RESIDENCE_ACCOUNT_PRINTRowChanged != null)) {
                    this.DS_RESIDENCE_ACCOUNT_PRINTRowChanged(this, new DS_RESIDENCE_ACCOUNT_PRINTRowChangeEvent(((DS_RESIDENCE_ACCOUNT_PRINTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.DS_RESIDENCE_ACCOUNT_PRINTRowChanging != null)) {
                    this.DS_RESIDENCE_ACCOUNT_PRINTRowChanging(this, new DS_RESIDENCE_ACCOUNT_PRINTRowChangeEvent(((DS_RESIDENCE_ACCOUNT_PRINTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.DS_RESIDENCE_ACCOUNT_PRINTRowDeleted != null)) {
                    this.DS_RESIDENCE_ACCOUNT_PRINTRowDeleted(this, new DS_RESIDENCE_ACCOUNT_PRINTRowChangeEvent(((DS_RESIDENCE_ACCOUNT_PRINTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.DS_RESIDENCE_ACCOUNT_PRINTRowDeleting != null)) {
                    this.DS_RESIDENCE_ACCOUNT_PRINTRowDeleting(this, new DS_RESIDENCE_ACCOUNT_PRINTRowChangeEvent(((DS_RESIDENCE_ACCOUNT_PRINTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void RemoveDS_RESIDENCE_ACCOUNT_PRINTRow(DS_RESIDENCE_ACCOUNT_PRINTRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                Ds_Residence_Account_Print ds = new Ds_Residence_Account_Print();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "DS_RESIDENCE_ACCOUNT_PRINTDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class DS_RESIDENCE_ACCOUNT_PRINTRow : global::System.Data.DataRow {
            
            private DS_RESIDENCE_ACCOUNT_PRINTDataTable tableDS_RESIDENCE_ACCOUNT_PRINT;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal DS_RESIDENCE_ACCOUNT_PRINTRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableDS_RESIDENCE_ACCOUNT_PRINT = ((DS_RESIDENCE_ACCOUNT_PRINTDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string RECEIPTNO {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTNOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RECEIPTNO\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTNOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string RECEIPTDATE {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTDATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RECEIPTDATE\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTDATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string RECEIPTREFNO {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTREFNOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RECEIPTREFNO\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTREFNOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string RECEIPTRID {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTRIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RECEIPTRID\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTRIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string FINYEAR {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.FINYEARColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FINYEAR\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.FINYEARColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string RECEIPTYEAR {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTYEARColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RECEIPTYEAR\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTYEARColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string RECEIPTMONTH {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTMONTHColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RECEIPTMONTH\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTMONTHColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string FORTHEYEAR {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.FORTHEYEARColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FORTHEYEAR\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.FORTHEYEARColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string SUBSCRIPTION {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.SUBSCRIPTIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SUBSCRIPTION\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.SUBSCRIPTIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string SALARY {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.SALARYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SALARY\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.SALARYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string FOODEXPENSE {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.FOODEXPENSEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FOODEXPENSE\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.FOODEXPENSEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string CONTRIBUTION {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.CONTRIBUTIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CONTRIBUTION\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.CONTRIBUTIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string EIDALFITR {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.EIDALFITRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EIDALFITR\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.EIDALFITRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string EIDALADHA {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.EIDALADHAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EIDALADHA\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.EIDALADHAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string COCUNUT {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.COCUNUTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COCUNUT\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.COCUNUTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string OTHER {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.OTHERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OTHER\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.OTHERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string TOTALAMOUNT {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.TOTALAMOUNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TOTALAMOUNT\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.TOTALAMOUNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string RECEIPTTYPE {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTTYPEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RECEIPTTYPE\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTTYPEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string RECEIPTDETAILS {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTDETAILSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RECEIPTDETAILS\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTDETAILSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string REMARKS {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.REMARKSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REMARKS\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.REMARKSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string PRINTED {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.PRINTEDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PRINTED\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.PRINTEDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string STATUS {
                get {
                    try {
                        return ((string)(this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.STATUSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'STATUS\' in table \'DS_RESIDENCE_ACCOUNT_PRINT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.STATUSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsRECEIPTNONull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTNOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetRECEIPTNONull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTNOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsRECEIPTDATENull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTDATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetRECEIPTDATENull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTDATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsRECEIPTREFNONull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTREFNOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetRECEIPTREFNONull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTREFNOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsRECEIPTRIDNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTRIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetRECEIPTRIDNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTRIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsFINYEARNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.FINYEARColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetFINYEARNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.FINYEARColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsRECEIPTYEARNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTYEARColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetRECEIPTYEARNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTYEARColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsRECEIPTMONTHNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTMONTHColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetRECEIPTMONTHNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTMONTHColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsFORTHEYEARNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.FORTHEYEARColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetFORTHEYEARNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.FORTHEYEARColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsSUBSCRIPTIONNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.SUBSCRIPTIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetSUBSCRIPTIONNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.SUBSCRIPTIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsSALARYNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.SALARYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetSALARYNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.SALARYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsFOODEXPENSENull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.FOODEXPENSEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetFOODEXPENSENull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.FOODEXPENSEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsCONTRIBUTIONNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.CONTRIBUTIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetCONTRIBUTIONNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.CONTRIBUTIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsEIDALFITRNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.EIDALFITRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetEIDALFITRNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.EIDALFITRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsEIDALADHANull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.EIDALADHAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetEIDALADHANull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.EIDALADHAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsCOCUNUTNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.COCUNUTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetCOCUNUTNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.COCUNUTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsOTHERNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.OTHERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetOTHERNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.OTHERColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTOTALAMOUNTNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.TOTALAMOUNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTOTALAMOUNTNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.TOTALAMOUNTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsRECEIPTTYPENull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTTYPEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetRECEIPTTYPENull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTTYPEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsRECEIPTDETAILSNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTDETAILSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetRECEIPTDETAILSNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.RECEIPTDETAILSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsREMARKSNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.REMARKSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetREMARKSNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.REMARKSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsPRINTEDNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.PRINTEDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetPRINTEDNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.PRINTEDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsSTATUSNull() {
                return this.IsNull(this.tableDS_RESIDENCE_ACCOUNT_PRINT.STATUSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetSTATUSNull() {
                this[this.tableDS_RESIDENCE_ACCOUNT_PRINT.STATUSColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public class DS_RESIDENCE_ACCOUNT_PRINTRowChangeEvent : global::System.EventArgs {
            
            private DS_RESIDENCE_ACCOUNT_PRINTRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public DS_RESIDENCE_ACCOUNT_PRINTRowChangeEvent(DS_RESIDENCE_ACCOUNT_PRINTRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public DS_RESIDENCE_ACCOUNT_PRINTRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591